[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts =
    -ra
    --browser chromium
    --html=reports/report.html
    --self-contained-html

markers =
    smoke: quick checks for critical paths
    regression: broader coverage tests
    negative: negative scenarios
    pim: OrangeHRM PIM module tests
    claim: Claims test cases